services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200" 
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080" 
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Recruitment
      SPRING_DATASOURCE_USERNAME: intern
      SPRING_DATASOURCE_PASSWORD: password

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: intern
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Recruitment
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: